ros__parameters:
  frame_id: "laser"
  serial_number: ""
  intensity: false
  time_offset: -0.08
  min_ang: -2.35619 # -135 degrees
  max_ang: 2.35619 # 135 degrees
  range_max: 10.0
  scan_topic: "/scan"
