ros__parameters:
  update_frequency: 10.0
  publish_frequency: 10.0

  use_sim_time: false

  global_frame: "odom"
  robot_base_frame: "base_link"
  robot_radius: 0.0
  # footprint: To be set by the robot specific configuration
  footprint_padding: 0.09

  resolution: 0.05
  track_unknown_space: False
  always_send_full_costmap: True

  rolling_window: True
  width: 5
  height: 5

  plugins: ["obstacle_laser_layer", "inflation_layer"]

  inflation_layer:
    plugin: "nav2_costmap_2d::InflationLayer"
    cost_scaling_factor: 2.58
    inflation_radius: 1.2

  obstacle_laser_layer:
    plugin: "nav2_costmap_2d::ObstacleLayer"
    enabled: True
    observation_sources: scan
    footprint_clearing_enabled: True
    scan:
      topic: "/scan"
      expected_update_rate: 0.2 # seconds
      max_obstacle_height: 2.0
      clearing: True
      marking: True
      observation_persistence: 0.0
      inf_is_valid: True
      data_type: "LaserScan"
      raytrace_max_range: 6.0
      raytrace_min_range: 0.0
      obstacle_max_range: 5.5
      obstacle_min_range: 0.0
