ros__parameters:
  use_sim_time: false
  controller_frequency: 50.0
  min_x_velocity_threshold: 0.001
  min_y_velocity_threshold: 0.0
  min_theta_velocity_threshold: 0.001
  failure_tolerance: 0.3
  progress_checker_plugin: "progress_checker"
  goal_checker_plugins: ["general_goal_checker"]
  controller_plugins: ["FollowPath"]
  odom_topic: "/mobile_base_controller/odom"
  speed_limit_topic: "/speed_limit"

  # Progress checker parameters
  progress_checker:
    plugin: "nav2_controller::SimpleProgressChecker"
    required_movement_radius: 0.5
    movement_time_allowance: 10.0
  # Goal checker parameters
  general_goal_checker:
    plugin: "nav2_controller::SimpleGoalChecker"
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.15
    stateful: True
  # MPPI parameters
  FollowPath:
    plugin: "nav2_mppi_controller::MPPIController"
    time_steps: 56
    model_dt: 0.05
    batch_size: 2000
    vx_std: 0.4
    vx_min: 0.0
    vx_max: 1.0
    vy_std: 0.0
    vy_min: 0.0
    vy_max: 0.0
    wz_std: 0.4
    wz_min: -2.0
    wz_max: 2.0
    ax_max: 1.0
    ax_min: 0.0
    ay_max: 0.0
    ay_min: 0.0
    iteration_count: 1
    prune_distance: 1.7
    transform_tolerance: 0.3
    temperature: 0.3
    gamma: 0.015
    motion_model: "DiffDrive"
    visualize: false
    reset_period: 1.0 # (only in Humble)
    TrajectoryVisualizer:
      trajectory_step: 5
      time_step: 3
    AckermannConstrains:
      min_turning_r: 0.0
    critics:
      [
        "ConstraintCritic",
        "CostCritic",
        "GoalCritic",
        "GoalAngleCritic",
        "PathAlignCritic",
        "PathFollowCritic",
        "PathAngleCritic",
        "PreferForwardCritic",
      ]
    ConstraintCritic:
      enabled: true
      cost_power: 1
      cost_weight: 4.0
    GoalCritic:
      enabled: true
      cost_power: 1
      cost_weight: 5.0
      threshold_to_consider: 1.4
    GoalAngleCritic:
      enabled: true
      cost_power: 1
      cost_weight: 3.0
      threshold_to_consider: 0.5
    PreferForwardCritic:
      enabled: true
      cost_power: 1
      cost_weight: 5.0
      threshold_to_consider: 0.5
    CostCritic:
      enabled: true
    PathAlignCritic:
      enabled: true
      cost_power: 1
      cost_weight: 20.0
      max_path_occupancy_ratio: 0.05
      trajectory_point_step: 3
      threshold_to_consider: 0.5
      offset_from_furthest: 20
      use_path_orientations: false
    PathFollowCritic:
      enabled: true
      cost_power: 1
      cost_weight: 5.0
      offset_from_furthest: 5
      threshold_to_consider: 1.4
    PathAngleCritic:
      enabled: true
      cost_power: 1
      cost_weight: 2.0
      offset_from_furthest: 4
      threshold_to_consider: 0.5
      max_angle_to_furthest: 1.0
      mode: 0
