ros__parameters:
  use_sim_time: false
  input_topic: "/scan_raw"
  output_topic: "/scan"

  filter1:
    name: range
    type: laser_filters/LaserScanRangeFilter
    params:
      lower_threshold: 0.0
      upper_threshold: 25.0
      lower_replacement_value: -.inf
      upper_replacement_value: .inf

  filter2:
    name: footprint_filter
    type: pal_laser_filters/LaserScanFootprintFilter
    params:
      footprint_type: "polygon"
      footprint: "[[0.1, 0.1], [-0.1, 0.1], [-0.1, -0.1], [0.1, -0.1]]"
