/actuators:
  raw_data:
    position_port: act_position
    effort_port: act_current
    mode_port: act_control_mode
    position_cmd_port: ref_position
    velocity_cmd_port: ref_velocity
    effort_cmd_port: ref_current
    mode_cmd_port: ref_control_mode
    current_limit_cmd_port: ref_limit_current
    absolute_encoder_position_port: act_abs_position
    pids_port: act_pids
    ff_term_port: act_ff_term
    pids_cmd_port: ref_pids
    ff_term_cmd_port: ref_ff_term

/joint_mode_black_list: ['torso_lift_controller']


/e_stop:
  raw_data:
    e_stop_port: emergency_stop_state

/ros_control_component:
  ignore_read_errors: false
