# Default initial positions for tiago_pro's ros2_control fake system

initial_positions:
  arm_left_1_joint: 0
  arm_left_2_joint: 0
  arm_left_3_joint: 0
  arm_left_4_joint: 0
  arm_left_5_joint: 0
  arm_left_6_joint: 0
  arm_left_7_joint: 0
  arm_right_1_joint: 0
  arm_right_2_joint: 0
  arm_right_3_joint: 0
  arm_right_4_joint: 0
  arm_right_5_joint: 0
  arm_right_6_joint: 0
  arm_right_7_joint: 0
  head_1_joint: 0
  head_2_joint: 0
  torso_lift_joint: 0
  gripper_left_finger_joint: 0
  gripper_right_finger_joint: 0