# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_left_controller_controller
    - arm_right_controller_controller
    - torso_controller_controller
    - head_controller_controller
    - gripper_left_controller_controller
    - gripper_right_controller_controller

  arm_left_controller_controller:
    type: FollowJointTrajectory
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
    action_ns: follow_joint_trajectory
    default: true
  arm_right_controller_controller:
    type: FollowJointTrajectory
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
    action_ns: follow_joint_trajectory
    default: true
  torso_controller_controller:
    type: FollowJointTrajectory
    joints:
      - torso_lift_joint
    action_ns: follow_joint_trajectory
    default: true
  head_controller_controller:
    type: FollowJointTrajectory
    joints:
      - head_1_joint
      - head_2_joint
    action_ns: follow_joint_trajectory
    default: true
  gripper_left_controller_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_left_finger_joint
    action_ns: follow_joint_trajectory
    default: true
  gripper_right_controller_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_right_finger_joint
    action_ns: follow_joint_trajectory
    default: true