<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Base with tool changer-->
    <xacro:macro name="inertial_base_link_tc">
        <inertial>
            <origin xyz="-0.000111195944040731 -5.20000467719152E-05 0.04682714296137" rpy="0 0 0" />
            <mass value="0.351833020899102" />
            <inertia ixx="0.000212702588837237" ixy="-1.5724450163606E-07" ixz="4.66935789777261E-07" iyy="0.000159938323491697" iyz="-1.90446642900145E-07" izz="0.000254149142086845" />
        </inertial>
    </xacro:macro>

    <!-- Base without tool changer-->
    <xacro:macro name="inertial_base_link_ntc">
        <inertial>
            <origin xyz="6.0291E-05 -0.00013653 -0.0051371" rpy="0 0 0" />
            <mass value="0.64278" />
            <inertia ixx="0.00033701" ixy="-8.3235E-07" ixz="5.4122E-07" iyy="0.00042750" iyz="-4.3734E-07" izz="0.00048564" />
        </inertial>
    </xacro:macro>

    <!-- Inner finger -->
    <xacro:macro name="inertial_inner_finger_link">
        <inertial>
            <origin xyz="-1.7347E-18 0.024759 0" rpy="0 0 0" />
            <mass value="0.018619" />
            <inertia ixx="4.8806E-06" ixy="-7.6762E-22" ixz="1.0244E-22" iyy="2.5471E-07" iyz="-1.1841E-21" izz="4.9573E-06" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="origin_inner_finger_joint" params="reflect offset">
        <origin xyz="0 ${reflect * 0.013977} ${0.078832 + offset}" rpy="1.5708 0.83776 ${reflect * 1.5708}" />
    </xacro:macro>

    <!-- Outer finger -->
    <xacro:macro name="inertial_outer_finger_link">
        <inertial>
            <origin xyz="-0.00128298420356912 0.0143974756929021 1.5011142385525E-15" rpy="0 0 0" />
            <mass value="0.0159887772377711" />
            <inertia ixx="5.98786243781872E-06" ixy="-5.21728921919786E-07" ixz="-7.65398863989897E-20" iyy="4.87250835241547E-07" iyz="-7.03393901384231E-19" izz="6.14972693188202E-06" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="origin_outer_finger_joint" params="reflect offset">
        <origin xyz="0 ${reflect * 0.0288} ${0.0743 + offset}" rpy="1.5708 0.83776 ${reflect * 1.5708}" />
    </xacro:macro>

    <!-- Fingertip -->
    <xacro:macro name="inertial_fingertip_link">
        <inertial>
            <origin xyz="-0.000864586242839444 0.0119290372347422 -2.732444563276E-11" rpy="0 0 0" />
            <mass value="0.0335029606041878" />
            <inertia ixx="3.6391786422032E-06" ixy="3.4052204633865E-07" ixz="-1.41918626749374E-14" iyy="1.70950026855986E-06" iyz="-4.24736685249643E-14" izz="2.84428135741107E-06" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="origin_fingertip_joint" params="reflect">
        <origin xyz="0 0.05 0" rpy="0 0 0.83776" />
    </xacro:macro>

</robot>
