<?xml version="1.0"?>
<!-- 
  Copyright (c) 2024 PAL Robotics S.L. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="palm" params="name parent reflect *origin">
        <!-- PALM MACRO -->
        <xacro:property name="palm_link_z" value="0.095"/>  
        <xacro:include filename="$(find pal_urdf_utils)/urdf/deg_to_rad.urdf.xacro" />
        <xacro:property name="x_coord"      value="${0 if reflect == 1 else -180}"/>

        <link name="${name}_palm_link">
            <inertial>
                <origin xyz="-0.009300 0 -${palm_link_z/2}" rpy="0 0 0"/>
                <mass value="0.4154"/>
                <inertia
                    ixx="7.54436e-4" ixy="0.0" ixz="0.0"
                    iyy="3.7004e-4" iyz="0.0"
                    izz="4.99645e-4"/>
            </inertial>
            <visual>
                <geometry>
                    <mesh filename="package://allegro_hand_description/meshes/base_link.STL" scale="${reflect} 1 1" />
                </geometry>
                <origin rpy="${x_coord*deg_to_rad} ${x_coord*deg_to_rad} 0" xyz="0 0 0 "/>
                <material name="black">
                    <color rgba="0.2 0.2 0.2 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="-0.009300 0 -${palm_link_z/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="0.0408 0.1130 ${palm_link_z}"/>
                </geometry>
            </collision>
        </link>

        <joint name="${name}_palm_joint" type="fixed">
            <parent link="${parent}" />
            <child link="${name}_palm_link" />
            <xacro:insert_block name="origin"/>
            <axis xyz="0 0 0" />
        </joint>
    </xacro:macro>
</robot>