ball_screw_efficiency: 0.0
ball_screw_lead: 0.0
motor_torque_constant: -0.03
torque_sensor_offset: 0.0
reduction_ratio: 101.1
actuator_names:
  - arm_right_6_motor
check_mode: false

# This parametres are random, they have not been identified

motor_inertia: 1.e-06
static_friction: 0.0
viscous_friction: 0.0
joint_elasticity: 993.0
joint_elasticity_damping: -20.0
