ball_screw_efficiency: 0.0
ball_screw_lead: 0.0
motor_torque_constant: 0.103
torque_sensor_offset: 0.0
reduction_ratio: 101.1
actuator_names:
  - arm_right_7_motor
check_mode: false

motor_inertia: 2.e-06
static_friction: 0.05
viscous_friction: 0.05
joint_elasticity: 993.0
joint_elasticity_damping: 1

