ball_screw_efficiency: 0.0
ball_screw_lead: 0.0
motor_torque_constant: -0.17
torque_sensor_offset: 0.0
reduction_ratio: 101.0
actuator_names:
  - arm_right_5_motor
check_mode: false

motor_inertia: 4.9e-06
static_friction: 0.0
viscous_friction: 0.0
joint_elasticity: 2033.0
joint_elasticity_damping: 1

