ros__parameters:
  update_frequency: 5.0
  publish_frequency: 1.0

  use_sim_time: false

  global_frame: "map"
  robot_base_frame: "base_link"
  robot_radius: 0.36
  footprint: ""
  footprint_padding: 0.09

  resolution: 0.05
  track_unknown_space: True
  always_send_full_costmap: True

  plugins: ["static_layer", "obstacle_laser_layer", "inflation_layer"]

  obstacle_laser_layer:
    plugin: "nav2_costmap_2d::ObstacleLayer"
    enabled: True
    observation_sources: scan
    combination_method: 0
    footprint_clearing_enabled: True
    scan:
      topic: "/scan"
      expected_update_rate: 0.2 # seconds
      max_obstacle_height: 2.0
      clearing: True
      marking: True
      observation_persistence: 2.0
      inf_is_valid: False
      data_type: "LaserScan"
      raytrace_max_range: 15.0
      raytrace_min_range: 0.0
      obstacle_max_range: 14.0
      obstacle_min_range: 0.0

  static_layer:
    plugin: "nav2_costmap_2d::StaticLayer"
    map_subscribe_transient_local: True

  inflation_layer:
    plugin: "nav2_costmap_2d::InflationLayer"
    cost_scaling_factor: 2.58
    inflation_radius: 1.2
