ros__parameters:
  update_frequency: 1.0
  publish_frequency: 1.0

  use_sim_time: false

  global_frame: "map"
  robot_base_frame: "base_link"
  # robot_radius: To be set by the robot specific configuration
  footprint: ""

  resolution: 0.05
  track_unknown_space: true
  always_send_full_costmap: True

  rolling_window: True
  width: 100
  height: 100

  plugins: ["static_layer", "obstacle_laser_layer", "inflation_layer"]
  filters: ["keepout_filter", "inflation_layer", "speed_filter"] # Using Inflation in Keepout for https://github.com/open-navigation/navigation2/issues/1263

  obstacle_laser_layer:
    plugin: "nav2_costmap_2d::ObstacleLayer"
    enabled: True
    observation_sources: scan
    combination_method: 0 # can erase static layer
    footprint_clearing_enabled: False
    scan:
      topic: "/scan"
      expected_update_rate: 0.2 # seconds
      max_obstacle_height: 2.0
      clearing: True
      marking: True
      data_type: "LaserScan"
      raytrace_max_range: 9.5
      raytrace_min_range: 0.0
      obstacle_max_range: 10.0
      obstacle_min_range: 0.0

  static_layer:
    plugin: "nav2_costmap_2d::StaticLayer"
    map_subscribe_transient_local: True

  inflation_layer:
    plugin: "nav2_costmap_2d::InflationLayer"
    cost_scaling_factor: 3.0
    inflation_radius: 0.8

  keepout_filter:
    plugin: "nav2_costmap_2d::KeepoutFilter"
    enabled: True
    filter_info_topic: "/keepout_map_mask/mask_info"

  speed_filter:
    plugin: "nav2_costmap_2d::SpeedFilter"
    enabled: True
    filter_info_topic: "/speed_map_mask/mask_info"
    speed_limit_topic: "/speed_limit"
