ros__parameters:
  planner_plugins: ["GridBased", "FunctionPlanner"]
  use_sim_time: false
  expected_planner_frequency: 20.0

  GridBased:
    plugin: "nav2_smac_planner/SmacPlanner2D"
    tolerance: 0.125                      # tolerance for planning if unable to reach exact pose, in meters
    downsample_costmap: false             # whether or not to downsample the map
    downsampling_factor: 1                # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
    allow_unknown: true                   # allow traveling in unknown space
    max_iterations: 1000000               # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
    max_on_approach_iterations: 1000      # maximum number of iterations to attempt to reach goal once in tolerance
    max_planning_time: 2.0                # max time in s for planner to plan, smooth
    cost_travel_multiplier: 7.5           # Cost multiplier to apply to search to steer away from high cost areas. Larger values will place in the center of aisles more exactly (if non-`FREE` cost potential field exists) but take slightly longer to compute. To optimize for speed, a value of 1.0 is reasonable. A reasonable tradeoff value is 2.0. A value of 0.0 effective disables steering away from obstacles and acts like a naive binary search A*.
    use_final_approach_orientation: false # Whether to set the final path pose at the goal's orientation to the requested orientation (false) or in line with the approach angle so the robot doesn't rotate to heading (true)
    smoother:
      max_iterations: 1000
      w_smooth: 0.3
      w_data: 0.2
      tolerance: 1.0e-10
  FunctionPlanner:
    plugin: "pal_nav2_planners::FunctionPlanner"
    interpolation_resolution: 0.1
    functions: ["1-sqrt(1-x^2)", "1+sqrt(1-x^2)"]   # Vector of functions to use for the planner plugin (e.g. circle of radius 1) expressed in explicit form y = f(x). This is a dynamic parameter, can be changed at runtime.
    ranges: "[[-1.0, 1.0], [-1.0, 1.0]]"            # Ranges in which each function is defined. This is a dynamic parameter, can be changed at runtime.  