/play_motion2:
  ros__parameters:
    motions:
      home:
        joints: [torso_lift_joint]
        times_from_start: [3.0]
        positions: [0.15]
        meta:
          name: Home
          usage: demo
          description: 'Go home'

      head_tour:
        joints: [head_1_joint, head_2_joint]
        times_from_start: [0.1, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0]
        positions: [0.0, 0.0,
                    0.7, 0.0,
                    0.7, 0.3,
                    0.7, -0.3,
                    0.7, 0.3,
                    -0.7, 0.3,
                    -0.7, -0.3,
                    0.0, 0.0]
        meta:
          name: Head Tour
          usage: demo
          description: 'head_tour'

      inspect_surroundings:
        joints: ['head_1_joint', 'head_2_joint']
        positions: [-0.88, 0.25,
                    -0.88, 0.25,
                    0.88, 0.25,
                    0.88, 0.25,
                    0., 0.25]
        times_from_start: [1.5, 2.0, 4.5, 5.0, 7.0]
        meta:
          name: Inspect Surroundings
          usage: demo
          description: 'Inspect surroundings around the robot'
